language: python

python:
  - "3.6"

install:
  - sudo apt-get update
  - sudo apt-get install unzip
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda info --all
  - conda env create --quiet --name sbmllint --file environment.yml
  - source activate sbmllint
  - pip install --upgrade pip
  - pip install matplotlib numpy pandas==0.22 urllib3 networkx tellurium nose

script:
  - cd data
  - unzip *.zip > t.out
  - cd ..
  - nosetests SBMLLint/tests
