language: python

install:
  - python3 -m venv test-sbmllint
  - source test-sbmllint/bin/activate
  - python setup.py install

script:
  - echo $PATH
  - cd ..; nosetests SBMLLint/tests
  - cp SBMLLint/data/biomodels/biomodels.zip .
  - unzip biomodels.zip BIOMD0000000232_url.xml
  - games BIOMD0000000232_url.xml
  - moiety_analysis BIOMD0000000232_url.xml
  - cd SBMLLint/examples/moiety_analysis/147
  - print_reactions BIOMD0000000147_url.xml
  - make_moiety_structure BIOMD0000000147_url.xml moieties_147.yml

