language: python

python:
  - "3.6"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - python3 -m venv test-sbmllint
  - source test-sbmllint/bin/activate
  - python setup.py install

script:
  - cd ..; nosetests SBMLLint/tests
  - cp SBMLLint/data/biomodels/biomodels.zip .
  - unzip biomodels.zip
  - games BIOMD0000000232_url.xml
  - moiety_analysis BIOMD0000000232_url.xml
  - SBMLLint/tools/moiety_analysis
