language: python

install:
  # Set up either with or without tellurium
  - bash setup_random.sh

script:
  # Run the tests
  - cd ..; nosetests SBMLLint/tests
  # Run the tools
  - cp SBMLLint/data/biomodels/biomodels.zip .
  - unzip biomodels.zip BIOMD0000000232.xml
  - games BIOMD0000000232.xml
  - lp_analysis --report_warnings True BIOMD0000000232.xml
  - moiety_analysis BIOMD0000000232.xml
  - cd SBMLLint/examples/moiety_analysis/147
  - print_reactions --kinetics True BIOMD0000000147.xml
  - make_moiety_structure BIOMD0000000147.xml moieties.yml
