name: sbmllint
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - numpy=1.16.3
  - pandas=0.22
  - python>=3.6.7
  - urllib3
  - networkx
  - xlrd
  - nose
  - pyyaml
  - scipy
  - python-libsbml
