# Configuration for SBMLLint

# Moieties and molecules may be ignored in the analysis. This is done
# to handle implicit moieties/molecules and as part of analyzing
# a model.
IGNORED_MOIETIES:
- DUMMY   # no ignored moiety
IGNORED_MOLECULES:
- DUMMY   # no ignored moiety

# Indicates if boundary reactions are checked
process_boundary_reactions: False

####
# Explicit declaration of moiety structures
# Remove the comments to activate this declaration of moiety structure
####
#moiety_structure:
#  ATP:  # Adenosine triphosphate
  # Moiety, stoichiometry
#  - A, 1
#  - P, 3
