
# Configuration for SBMLLint
# Implicit molecules are molecules that may be implicit
# in either the reactants or products.
ignored_molecules:
- IkBa_mRNA
- IkBe_mRNA

ignored_moieties:
- cytoplasm
- nucleus
- IkBa
- IkBb
- IkBe

# Indicates if boundary reactions are checked
process_boundary_reactions: False

# Explicit declaration of moiety structures
