# Configuration for SBMLLint
# Implicit molecules are molecules that may be implicit
# in either the reactants or products.
ignored_molecules:
- ADP
- AMP
- ATP
- degUb2
- degUb3
- degUb4
- degUb5
- degUb6
- degUb7
- degUb8

ignored_moieties:
- Agg
- Mis
- Nat
- ref
- Seq
- Source
- tot

# Indicates if boundary reactions are checked
process_boundary_reactions: False

# Explicit declaration of moiety structures
moiety_structure:
  Proteasome:
    - P, 1
  Ub2:
    - Ub, 2
  ADP:
  - ADP, 1
  AMP:
  - AMP, 1
  ATP:
  - ATP, 1
  AggP:
  - Agg, 1
  - P, 1
  AggP_Proteasome:
  - Proteasome, 1
  - Agg, 1
  - P, 1
  DUB:
  - DUB, 1
  E1:
  - E1, 1
  E1_Ub:
  - E1, 1
  - Ub, 1
  E2:
  - E2, 1
  E2_Ub:
  - E2, 1
  - Ub, 1
  E3:
  - E3, 1
  E3_MisP:
  - Mis, 1
  - E3, 1
  - P, 1
  MisP:
  - Mis, 1
  - P, 1
  MisP_Ub:
  - Mis, 1
  - Ub, 1
  - P, 1
  MisP_Ub2:
  - Mis, 1
  - Ub, 2
  - P, 1
  MisP_Ub3:
  - Mis, 1
  - Ub, 3
  - P, 1
  MisP_Ub4:
  - Mis, 1
  - Ub, 4
  - P, 1
  MisP_Ub4_Proteasome:
  - Proteasome, 1
  - Mis, 1
  - Ub, 4
  - P, 1
  MisP_Ub5:
  - Mis, 1
  - Ub, 5
  - P, 1
  MisP_Ub5_Proteasome:
  - Proteasome, 1
  - Mis, 1
  - Ub, 5
  - P, 1
  MisP_Ub6:
  - Mis, 1
  - Ub, 6
  - P, 1
  MisP_Ub6_Proteasome:
  - Proteasome, 1
  - Mis, 1
  - Ub, 6
  - P, 1
  MisP_Ub7:
  - Mis, 1
  - Ub, 7
  - P, 1
  MisP_Ub7_Proteasome:
  - Proteasome, 1
  - Mis, 1
  - Ub, 7
  - P, 1
  MisP_Ub8:
  - Mis, 1
  - Ub, 8
  - P, 1
  MisP_Ub8_Proteasome:
  - Proteasome, 1
  - Mis, 1
  - Ub, 8
  - P, 1
  NatP:
  - Nat, 1
  - P, 1
  Proteasome:
  - Proteasome, 1
  ROS:
  - ROS, 1
  SeqAggP:
  - Agg, 1
  - Seq, 1
  - P, 1
  Source:
  - Source, 1
  Ub:
  - Ub, 1
  Ub4:
  - Ub, 4
  Ub5:
  - Ub, 5
  degUb4:
  - deg, 1
  - Ub, 4
  degUb5:
  - deg, 1
  - Ub, 5
  degUb6:
  - deg, 1
  - Ub, 6
  degUb7:
  - deg, 1
  - Ub, 7
  degUb8:
  - deg, 1
  - Ub, 8
  refNatP:
  - Nat, 1
  - ref, 1
  totMisP:
  - Mis, 1
  - tot, 1
