# Configuration for SBMLLint
# Implicit molecules are molecules that may be implicit
# in either the reactants or products.
ignored_molecules:

ignored_moieties:
- B
- K
- PP
- P
- R

# Indicates if boundary reactions are checked
process_boundary_reactions: False

# Explicit declaration of moiety structures
moiety_structure:
  E1:
  - E1, 1
  E1_KKK:
  - KKK, 1
  - E1, 1
  E2:
  - E2, 1
  E2_P_KKK:
  - KKK, 1
  - E2, 1
  - P, 1
  K:
  - K, 1
  KK:
  - KK, 1
  KKK:
  - KKK, 1
  KKPase:
  - ase, 1
  - KK, 1
  - P, 1
  KKPase_PP_KK:
  - ase, 1
  - KK, 2
  - P, 3
  KKPase_P_KK:
  - ase, 1
  - KK, 2
  - P, 2
  KPase:
  - ase, 1
  - K, 1
  - P, 1
  KPase_PP_K:
  - ase, 1
  - K, 2
  - P, 3
  KPase_P_K:
  - ase, 1
  - K, 2
  - P, 2
  PP_K:
  - K, 1
  - P, 2
  PP_KK:
  - KK, 1
  - P, 2
  PP_KK_K:
  - KK, 1
  - K, 1
  - P, 2
  PP_KK_P_K:
  - KK, 1
  - K, 1
  - P, 3
  P_K:
  - K, 1
  - P, 1
  P_KK:
  - KK, 1
  - P, 1
  P_KKK:
  - KKK, 1
  - P, 1
  P_KKK_KK:
  - KKK, 1
  - KK, 1
  - P, 1
  P_KKK_P_KK:
  - KKK, 1
  - KK, 1
  - P, 2
