# Configuration for SBMLLint
# Implicit molecules are molecules that may be implicit
# in either the reactants or products.
ignored_molecules:

ignored_moieties:
- B
- K
- R

# Indicates if boundary reactions are checked
process_boundary_reactions: False

# Explicit declaration of moiety structures
moiety_structure:
  Cdc25:
  - Cdc25, 1
  Cdc25B:
  - Cdc25, 1
  - B, 1
  G1K:
  - G1, 1
  - K, 1
  G1R:
  - G1, 1
  - R, 1
  G2K:
  - G2, 1
  - K, 1
  G2R:
  - G2, 1
  - R, 1
  IE:
  - IE, 1
  IEB:
  - IE, 1
  - B, 1
  PG2:
  - PG2, 1
  PG2R:
  - PG2, 1
  - R, 1
  R:
  - R, 1
  UbE:
  - UbE, 1
  UbE2:
  - UbE2, 1
  UbE2B:
  - UbE2, 1
  - B, 1
  UbEB:
  - UbE, 1
  - B, 1
  Wee1:
  - Wee1, 1
  Wee1B:
  - Wee1, 1
  - B, 1
